---
title: "Housing trends in Minneapolis compared to crime"
output: html_notebook
date:  "Last updated: `r Sys.Date()`"
---

```{r, echo=FALSE, eval=FALSE, results="hide", message=FALSE, warning=FALSE}

library(tidyverse)
library(janitor)
library(lubridate)
library(ggthemes)
library(readxl)
library(gghighlight)
library(scales) #needed for stacked bar chart axis labels
library(aws.s3) #needed for uploading to amazon S3 server






crime <-  read_xlsx('./data/mpls_crimes_neighborhoods_2021.xlsx') %>% clean_names()

mpls <-  read_csv('./output/mpls_hood_index_2021.csv')

mpls <-  left_join(mpls, crime, by=c("place"="name_in_realtors_data"))



mpls <-  mpls %>% mutate(pct_chg_total = (total_2021-total_2019)/total_2019,
                         pct_chg_vio = (violent_2021-violent_2019)/violent_2019,
                         pct_chg_prop = (property_2021-property_2019)/property_2019,
                         crime_per10k = (total_2021/pop2020)*10000,
                         vio_per10k = (violent_2021/pop2020)*10000,
                         prop_per10k = (property_2021/pop2020)*10000)



```

```{r, echo=FALSE}
ggplot(mpls, aes(x=vio_per10k, y=msi_pctchange))+
  geom_point(stat="identity")+
  gghighlight(vio_per10k >=200 | msi_pctchange>=1, label_key = neighborhood, unhighlighted_params = list(size = 1, colour = alpha("blue", 0.4)))+
  scale_y_continuous(name= "Pct change Month Supply", label=scales::percent, breaks=seq(-1, 2, .5))+
  scale_x_continuous(name="Violent crimes per 10,000", breaks=seq(0,500, 50))+
  labs(title = "Violent crime per capita compared to percent change in months supply",
       subtitle = "Minneapolis neighborhoods 2021")
```


```{r, echo=FALSE}
ggplot(mpls, aes(x=vio_per10k, y=ppsf_pctchange))+
  geom_point(stat="identity")+
  gghighlight(vio_per10k >=200 | ppsf_pctchange<0, label_key = neighborhood, unhighlighted_params = list(size = 1, colour = alpha("blue", 0.4)))+
  scale_y_continuous(name= "Pct change price per square foot", label=scales::percent, breaks=seq(-.2, .5, .1))+
  scale_x_continuous(name="Violent crimes per 10,000", breaks=seq(0,500, 50))+
  labs(title = "Violent crime per capita compared to percent change in price per square foot",
       subtitle = "Minneapolis neighborhoods 2021")
```


```{r, echo=FALSE}
ggplot(mpls %>% filter(violent_2019>=15), aes(x=pct_chg_vio, y=msi_pctchange))+
  geom_point(stat="identity")+
  gghighlight(pct_chg_vio>1.5| msi_pctchange>1, label_key = neighborhood, unhighlighted_params = list(size = 1, colour = alpha("blue", 0.4)))+
  scale_y_continuous(name= "Pct change Month Supply", label=scales::percent, breaks=seq(-1, 2, .5))+
  scale_x_continuous(name="Pct change violent crime", label=scales::percent,  breaks=seq(-1,2, .5))+
  labs(title = "Percent change in violent crime compared to percent change in months supply",
       subtitle = "excludes neighborhoods with less than 15 violent crimes in 2019")
```


```{r, echo=FALSE}
ggplot(mpls %>% filter(violent_2019>=15), aes(x=pct_chg_vio, y=ppsf_pctchange))+
  geom_point(stat="identity")+
  gghighlight(pct_chg_vio>1.25| ppsf_pctchange<0, label_key = neighborhood, unhighlighted_params = list(size = 1, colour = alpha("blue", 0.4)))+
  scale_y_continuous(name= "Pct change price per square foot", label=scales::percent, breaks=seq(-.05, 1, .05))+
  scale_x_continuous(name="Pct change violent crime", label=scales::percent,  breaks=seq(-1,2, .5))+
  labs(title = "Pct change in violent crime compared to pct change in price per square ft",
       subtitle = "excludes neighborhoods with less than 15 violent crimes in 2019")
```



```{r, echo=FALSE}
ggplot(mpls , aes(x=vio_per10k, y=msi))+
  geom_point(stat="identity")+
  gghighlight(vio_per10k>250| msi>4, label_key = neighborhood, unhighlighted_params = list(size = 1, colour = alpha("blue", 0.4)))+
  scale_y_continuous(name= "months supply",  breaks=seq(0, 6.5, 1))+
  scale_x_continuous(name="Violent crime rate",  breaks=seq(0,380, 50))+
  labs(title = "Months supply versus violent crime rate",
       subtitle = "")
```

```{r, echo=FALSE}
ggplot(mpls , aes(x=prop_per10k, y=msi))+
  geom_point(stat="identity")+
  gghighlight(prop_per10k>650| msi>4, label_key = neighborhood, unhighlighted_params = list(size = 1, colour = alpha("blue", 0.4)))+
  scale_y_continuous(name= "months supply",  breaks=seq(0, 6.5, 1))+
  scale_x_continuous(name="Property crime rate",  breaks=seq(0,800, 50))+
  labs(title = "Months supply versus property crime rate",
       subtitle = "")
```


```{r, echo=FALSE}
ggplot(mpls, aes(x=pct_chg_prop, y=msi_pctchange))+
  geom_point(stat="identity")+
  gghighlight(pct_chg_prop>.75| msi_pctchange>1, label_key = neighborhood, unhighlighted_params = list(size = 1, colour = alpha("blue", 0.4)))+
  scale_y_continuous(name= "Pct change Month Supply", labels=scales::percent, breaks=seq(-1, 2, .5))+
  scale_x_continuous(name="Pct change property crime", labels=scales::percent,  breaks=seq(-1,1, .2))+
  labs(title = "Pct change in property crime compared to pct change in months supply",
       subtitle = "")
```



```{r, echo=FALSE}
ggplot(mpls, aes(x=ppsf, y=msi))+
  geom_point(stat="identity")+
  #gghighlight(pct_chg_prop>.75| msi_pctchange>1, label_key = neighborhood, unhighlighted_params = list(size = 1, colour = alpha("blue", 0.4)))+
  scale_y_continuous(name= "Months Supply",  breaks=seq(-1, 6, 1))+
  scale_x_continuous(name=" price per square foot", breaks=seq(0,500,50))+
  labs(title = "months supply and PPSF",
       subtitle = "Doesn't appear to be any relationship")
```


```{r, echo=FALSE, eval=FALSE, results="hide", message=FALSE, warning=FALSE}

#Load to this URL: http://strib-data-internal.s3-us-west-1.amazonaws.com/projects/HotHousingIndex/HotIndex.html
#this section will not run automatically when you run the whole page


Sys.setenv("AWS_ACCESS_KEY_ID" =  Sys.getenv("strib_public_key"),

           "AWS_SECRET_ACCESS_KEY" =Sys.getenv("strib_public_secrete_key"),
           "AWS_DEFAULT_REGION" = "us-west-1")



put_object(file = "mpls_hood_index_2021.nb.html", object = "projects/housing/mpls_hood_index_2021.nb.html", bucket = "strib-data-public")

put_object(file = "mpls_hood_index_2021.nb.html", object = "projects/housing/mpls_hood_index_2021.nb.html", bucket = "strib-data-public", acl=c("public-read"))
```

